# Generated by Django 5.1.1 on 2024-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('surname', models.CharField(max_length=80)),
                ('photo', models.ImageField(null=True, upload_to='media/')),
                ('last_creation_userid', models.IntegerField(null=True)),
                ('last_update_userid', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
